# Generated by Django 4.2.11 on 2024-03-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='staticobject',
            fields=[
                ('staticobject_id', models.AutoField(primary_key=True, serialize=False)),
                ('staticobject_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='object_coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_coordinate_x', models.FloatField()),
                ('object_coordinate_y', models.FloatField()),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, to='walkinter.brand')),
                ('staticobject', models.ForeignKey(db_column='staticobject_id', on_delete=django.db.models.deletion.CASCADE, to='walkinter.staticobject')),
            ],
        ),
    ]
