# Generated by Django 5.0.3 on 2024-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkinter", "0003_gpsdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpsdata",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
