# Generated by Django 5.0.3 on 2024-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkinter", "0004_alter_gpsdata_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpsdata",
            name="average_speed",
            field=models.FloatField(null=True),
        ),
    ]
