# Generated by Django 5.0.3 on 2024-04-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkinter", "0005_gpsdata_average_speed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z", models.FloatField()),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("z1", models.FloatField()),
            ],
        ),
    ]
