# Generated by Django 5.0.3 on 2024-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkinter", "0006_sensordata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorDataMagnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("z1", models.FloatField()),
            ],
        ),
    ]
