# Generated by Django 5.0.3 on 2024-05-15 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("walkinter", "0007_sensordatamagnet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object_coordinate",
            name="staticobject",
        ),
        migrations.DeleteModel(
            name="staticobject",
        ),
    ]
