# Generated by Django 5.0.3 on 2024-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("walkinter", "0008_remove_object_coordinate_staticobject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvgSpeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_speed", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
